In [20]:
import torch
import numpy as np

In [21]:
torch.randint(-100,100,(6,))


tensor([ 61, -28,  34, -20,  95,  93])

In [22]:
torch.tensor([[0.1,0.2,0.3],[0.3,0.4,0.5],[0.7,0.1,0.2]])

tensor([[0.1000, 0.2000, 0.3000],
        [0.3000, 0.4000, 0.5000],
        [0.7000, 0.1000, 0.2000]])

In [23]:

torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [27]:
torch.linspace(3,10,steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [28]:
torch.logspace(-10,10,5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [29]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
torch.empty((2,3),dtype=torch.int64)

tensor([[4489188110458735821, 4510805389542529434, 4539628425443069133],
        [4453159313463259955,          1045220557,                   0]])

In [41]:
prob = torch.tensor([0.1,0.9])

sample = torch.multinomial(prob,num_samples=10,replacement=True)

print(sample)

tensor([1, 1, 0, 1, 0, 1, 1, 1, 1, 1])


In [42]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [43]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [44]:
out = torch.triu(torch.ones(3,3))
out

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]])

In [54]:
out = torch.zeros(5,5).masked_fill((torch.tril(torch.ones(5,5)))==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [55]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [58]:
out = torch.zeros(2,3,4)
out=out.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [60]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,5,3])
tensor3 = torch.tensor([2,3,7])

out = torch.stack([tensor1,tensor2,tensor3])
out


tensor([[1, 2, 3],
        [1, 5, 3],
        [2, 3, 7]])

In [61]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
liner = nn.Linear(3,3,bias=False)
liner(sample)

tensor([-11.2964,   2.2236,   1.9770], grad_fn=<SqueezeBackward4>)

In [65]:
import torch.nn.functional as F

tensor = torch.tensor([1.,2.,3.])

F.softmax(tensor,dim=0)

tensor([0.0900, 0.2447, 0.6652])

In [66]:
vocab_size = 1000
dim=100

embeding = nn.Embedding(vocab_size,dim)

input_indice = torch.tensor([1,2,3,4])

out_emb = embeding(input_indice)

out_emb.shape


torch.Size([4, 100])

In [67]:
out_emb


tensor([[ 0.2473, -0.8188, -0.0365,  0.3115,  1.0104,  1.1856,  0.2171, -0.9139,
         -0.4285,  0.2134, -0.8165,  0.6592, -0.9285,  0.8515, -0.2524,  1.1245,
          0.1055,  0.2588, -2.0427, -0.6450,  0.7107,  0.4082, -0.3593,  0.2778,
         -0.7166,  0.4901,  0.1014,  0.5316,  0.8068, -0.3304,  0.0452, -0.3082,
          2.4677, -1.2330, -0.4255, -1.3756, -0.1311, -1.6461, -0.1878, -2.6195,
          1.7629, -0.8837, -1.0045,  0.5958,  0.9036, -1.7389, -0.4531, -0.6396,
          1.5171, -0.9283,  0.1504, -1.9891, -1.3113, -2.5463, -1.2092, -1.8916,
         -1.6892,  1.7225, -0.6239, -0.6728,  1.1663, -0.5597,  0.2141,  0.4311,
         -1.1724, -1.2260,  0.7720, -1.2835, -2.1890,  0.3807,  0.0251,  1.0551,
          0.0216,  1.0421,  0.2509, -0.3336, -0.2403,  0.0343,  0.9415,  0.1597,
          1.2200,  0.5839,  0.2128,  0.5678,  0.5247, -1.1692,  0.1252, -0.6780,
          0.6288,  0.5297,  0.5671, -1.2827,  1.1275,  0.4883,  1.0032, -0.4612,
         -1.1944, -0.7176, -